/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a user's preferences by user ID */
    get: operations['PreferencesController_getPreference'];
    put?: never;
    /** Create a user's preferences */
    post: operations['PreferencesController_createPreference'];
    /** Delete a user's preferences by user ID */
    delete: operations['PreferencesController_deletePreference'];
    options?: never;
    head?: never;
    /** Update a user's preferences by user ID */
    patch: operations['PreferencesController_updatePreference'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PreferencesResponseDto: {
      /**
       * @description User ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      userId: string;
      /**
       * @description Units
       * @example metric
       */
      units: string;
      /**
       * @description Theme
       * @example light
       */
      theme: string;
      /**
       * @description Date format
       * @example DD/MM/YYYY
       */
      dateFormat: string;
      /**
       * @description Time format
       * @example 12h
       */
      timeFormat: string;
      /**
       * Format: date-time
       * @description Created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    CreatePreferencesDto: {
      /**
       * @description Units
       * @example metric
       * @enum {string}
       */
      units: 'metric' | 'imperial';
      /**
       * @description Theme
       * @example light
       * @enum {string|null}
       */
      theme: 'light' | 'dark' | null;
      /**
       * @description Date format
       * @example DD/MM/YYYY
       * @enum {string}
       */
      dateFormat:
        | 'DD/MM/YYYY'
        | 'MM/DD/YYYY'
        | 'YYYY/MM/DD'
        | 'DD-MM-YYYY'
        | 'MM-DD-YYYY'
        | 'YYYY-MM-DD';
      /**
       * @description Time format
       * @example 12h
       * @enum {string}
       */
      timeFormat: '12h' | '24h';
    };
    UpdatePreferencesDto: {
      /**
       * @description Units
       * @example metric
       * @enum {string}
       */
      units?: 'metric' | 'imperial';
      /**
       * @description Theme
       * @example light
       * @enum {string|null}
       */
      theme?: 'light' | 'dark' | null;
      /**
       * @description Date format
       * @example DD/MM/YYYY
       * @enum {string}
       */
      dateFormat?:
        | 'DD/MM/YYYY'
        | 'MM/DD/YYYY'
        | 'YYYY/MM/DD'
        | 'DD-MM-YYYY'
        | 'MM-DD-YYYY'
        | 'YYYY-MM-DD';
      /**
       * @description Time format
       * @example 12h
       * @enum {string}
       */
      timeFormat?: '12h' | '24h';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  PreferencesController_getPreference: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User preferences retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User preferences not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PreferencesController_createPreference: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePreferencesDto'];
      };
    };
    responses: {
      /** @description User preferences created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PreferencesController_deletePreference: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User preferences deleted successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PreferencesController_updatePreference: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePreferencesDto'];
      };
    };
    responses: {
      /** @description User preferences updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PreferencesResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
