import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import { Sidebar } from '@repo/react-common/sidebar';

import { DesktopNav } from '@/components/Navigation/DesktopNav';
import { MobileHeader } from '@/components/Navigation/MobileHeader';
import { MobileNav } from '@/components/Navigation/MobileNav';
import { MobileNavDrawer } from '@/components/Navigation/MobileNavDrawer';
import { Providers } from '@/components/providers';
import { SidebarSlot } from '@/components/Sidebar';
import { ActionPanel } from '@/components/Sidebar/ActionPanel';
import { ToastNotifications } from '@/components/ToastNotifications';
import { getSession } from '@/lib/session';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Frontend tryout',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const isLoggedIn = session.isLoggedIn ?? false;

  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Providers>
          <div className="flex h-screen flex-col lg:flex-row">
            <div className="hidden w-1/5 min-w-64 lg:block">
              <Sidebar linkAs={Link}>
                <SidebarSlot />
              </Sidebar>
            </div>

            <div className="flex flex-1 flex-col overflow-hidden">
              <div className="hidden lg:block">
                <DesktopNav />
              </div>
              <div className="lg:hidden">
                <MobileHeader />
              </div>

              <main className="mb-16 flex-1 overflow-y-auto lg:mb-0">{children}</main>

              <div className="lg:hidden">
                <MobileNavDrawer />
                <MobileNav />
              </div>
            </div>
          </div>
          {isLoggedIn && <ActionPanel />}
          <ToastNotifications />
        </Providers>
      </body>
    </html>
  );
}
