import { Sidebar } from '@repo/react-common/sidebar';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { DesktopNav } from '@/components/navigation/DesktopNav';
import { MobileHeader } from '@/components/navigation/MobileHeader';
import { MobileNav } from '@/components/navigation/MobileNav';
import Providers from '@/components/providers';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Frontend tryout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Providers>
          <div className="flex h-screen flex-col lg:flex-row">
            <div className="hidden lg:block">
              <Sidebar />
            </div>

            <div className="flex flex-1 flex-col overflow-hidden">
              <div className="hidden lg:block">
                <DesktopNav />
              </div>
              <div className="lg:hidden">
                <MobileHeader />
              </div>

              <main className="flex-1 overflow-y-auto">{children}</main>

              <div className="lg:hidden">
                <MobileNav />
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
