export {
  NAME_MAX_LENGTH,
  CATEGORY_NAME_MAX_LENGTH,
  DESCRIPTION_MAX_LENGTH,
  COLOR_CODE_MAX_LENGTH,
  REMARKS_MAX_LENGTH,
} from '@repo/constants';

const DEFAULT_RESOURCE_THROTTLE = {
  GET_ALL: 60,
  GET: 20,
  POST: 10,
  PATCH: 20,
  DELETE: 20,
  GET_DELETE_IMPACT: 20,
} as const;

const DEFAULT_JOIN_TABLE_THROTTLE = {
  UPSERT: 120,
  REMOVE: 120,
} as const;

export const THROTTLE_TTL_MS = 60000;
export const THROTTLE_LIMITS = {
  TEST: 5,
  ITEMS: DEFAULT_RESOURCE_THROTTLE,
  CATEGORIES: DEFAULT_RESOURCE_THROTTLE,
  LISTS: DEFAULT_RESOURCE_THROTTLE,
  PACKS: DEFAULT_RESOURCE_THROTTLE,
  TRIPS: DEFAULT_RESOURCE_THROTTLE,
  ITEM_LIST: DEFAULT_JOIN_TABLE_THROTTLE,
  ITEM_PACK: DEFAULT_JOIN_TABLE_THROTTLE,
  LIST_PACK: DEFAULT_JOIN_TABLE_THROTTLE,
} as const;
