// Product
export const NAME_MAX_LENGTH = 128;
export const DESCRIPTION_MAX_LENGTH = 1000;
export const COLOR_CODE_MAX_LENGTH = 64; // TODO: decide on color code implementation. Custom strings or rgb/hex/etc.
export const REMARKS_MAX_LENGTH = 1000;

// Throttling
const DEFAULT_RESOURCE_THROTTLE = {
  GET_ALL: 60,
  GET: 20,
  POST: 10,
  PATCH: 20,
  DELETE: 5,
  GET_DELETE_IMPACT: 5,
} as const;

const DEFAULT_JOIN_TABLE_THROTTLE = {
  UPSERT: 10,
  REMOVE: 10,
} as const;

export const THROTTLE_TTL_MS = 60000;
export const THROTTLE_LIMITS = {
  TEST: 5,
  ITEMS: DEFAULT_RESOURCE_THROTTLE,
  CATEGORIES: DEFAULT_RESOURCE_THROTTLE,
  LISTS: DEFAULT_RESOURCE_THROTTLE,
  PACKS: DEFAULT_RESOURCE_THROTTLE,
  TRIPS: DEFAULT_RESOURCE_THROTTLE,
  ITEM_LIST: DEFAULT_JOIN_TABLE_THROTTLE,
  ITEM_PACK: DEFAULT_JOIN_TABLE_THROTTLE,
  LIST_PACK: DEFAULT_JOIN_TABLE_THROTTLE,
} as const;
