/*
  Warnings:

  - The values [GUEST_SESSION_EXPIRED] on the enum `AuditEventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "app_auth"."AuditEventType_new" AS ENUM ('TOKEN_REUSE_DETECTED', 'SUSPICIOUS_ACTIVITY', 'BFF_SECRET_MISMATCH', 'INTERNAL_SERVER_ERROR', 'EMAIL_SEND_FAILED', 'USER_LOGIN_FAILED', 'INVALID_SESSION', 'INVALID_TOKEN', 'SECURITY_RATE_LIMIT_EXCEEDED', 'VALIDATION_ERROR', 'AUTHORIZATION_FAILED', 'RESOURCE_NOT_FOUND', 'CONFLICT_ERROR', 'USER_REGISTERED', 'USER_LOGIN_SUCCESS', 'USER_DELETED', 'TOKEN_REFRESHED', 'TOKEN_REFRESHED_RACE_CONDITION', 'SESSION_EXPIRED', 'USER_LOGOUT', 'USER_LOGOUT_ALL_DEVICES', 'PASSWORD_CHANGED', 'ACCOUNT_DELETION_ACCESS_ATTEMPT', 'SCHEDULED_TASK', 'HTTP_ERROR', 'PASSWORD_FORGOTTEN', 'PASSWORD_RESET', 'CANCEL_ACCOUNT_DELETION', 'EMAIL_VERIFIED', 'EMAIL_VERIFICATION_RESENT', 'GUEST_SESSION_CREATED');
ALTER TABLE "app_auth"."AuditLog" ALTER COLUMN "eventType" TYPE "app_auth"."AuditEventType_new" USING ("eventType"::text::"app_auth"."AuditEventType_new");
ALTER TYPE "app_auth"."AuditEventType" RENAME TO "AuditEventType_old";
ALTER TYPE "app_auth"."AuditEventType_new" RENAME TO "AuditEventType";
DROP TYPE "app_auth"."AuditEventType_old";
COMMIT;
