/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/item': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all items */
    get: operations['ItemController_getItems'];
    put?: never;
    /** Create an item */
    post: operations['ItemController_createItem'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/item/{id}/delete-impact': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the impact of deleting an item by ID. Details the lists, packs, and trips that will be affected. */
    get: operations['ItemController_getItemDeleteImpact'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/item/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an item by ID */
    get: operations['ItemController_getItem'];
    put?: never;
    post?: never;
    /** Delete an item by ID */
    delete: operations['ItemController_deleteItem'];
    options?: never;
    head?: never;
    /** Update an item by ID */
    patch: operations['ItemController_updateItem'];
    trace?: never;
  };
  '/category': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all categories */
    get: operations['CategoryController_getCategories'];
    put?: never;
    /** Create a category */
    post: operations['CategoryController_createCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/category/{id}/delete-impact': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the impact of deleting a category by ID. Gives the number of items in the category. */
    get: operations['CategoryController_getCategoryDeleteImpact'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/category/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a category by ID */
    get: operations['CategoryController_getCategory'];
    put?: never;
    post?: never;
    /** Delete a category by ID */
    delete: operations['CategoryController_deleteCategory'];
    options?: never;
    head?: never;
    /** Update a category by ID */
    patch: operations['CategoryController_updateCategory'];
    trace?: never;
  };
  '/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all lists */
    get: operations['ListController_getLists'];
    put?: never;
    /** Create a list */
    post: operations['ListController_createList'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/list/{id}/delete-impact': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the impact of deleting a list by ID. Details the packs and trips that will be affected. */
    get: operations['ListController_getListDeleteImpact'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/list/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a list by ID */
    get: operations['ListController_getList'];
    put?: never;
    post?: never;
    /** Delete a list by ID */
    delete: operations['ListController_deleteList'];
    options?: never;
    head?: never;
    /** Update a list by ID */
    patch: operations['ListController_updateList'];
    trace?: never;
  };
  '/pack': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all packs */
    get: operations['PackController_getPacks'];
    put?: never;
    /** Create a pack */
    post: operations['PackController_createPack'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pack/{id}/delete-impact': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the impact of deleting a pack by ID. Details the trips that will be affected. */
    get: operations['PackController_getPackDeleteImpact'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pack/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a pack by ID */
    get: operations['PackController_getPack'];
    put?: never;
    post?: never;
    /** Delete a pack by ID */
    delete: operations['PackController_deletePack'];
    options?: never;
    head?: never;
    /** Update a pack by ID */
    patch: operations['PackController_updatePack'];
    trace?: never;
  };
  '/trip': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all trips */
    get: operations['TripController_getTrips'];
    put?: never;
    /** Create a trip */
    post: operations['TripController_createTrip'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/trip/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a trip by ID */
    get: operations['TripController_getTrip'];
    put?: never;
    post?: never;
    /** Delete a trip by ID */
    delete: operations['TripController_deleteTrip'];
    options?: never;
    head?: never;
    /** Update a trip by ID */
    patch: operations['TripController_updateTrip'];
    trace?: never;
  };
  '/item-list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upsert an item to a list */
    post: operations['ItemListController_upsertItemOnList'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/item-list/{itemId}/{listId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove an item from a list */
    delete: operations['ItemListController_removeItemFromList'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/item-pack': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upsert an item to a pack */
    post: operations['ItemPackController_upsertItemInPack'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/item-pack/{itemId}/{packId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove an item from a pack */
    delete: operations['ItemPackController_removeItemFromPack'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/list-pack': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upsert a list to a pack */
    post: operations['ListPackController_upsertListInPack'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/list-pack/{listId}/{packId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a list from a pack */
    delete: operations['ListPackController_removeListFromPack'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CategoryResponseDto: {
      /**
       * @description Category uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Category name
       * @example Category name
       */
      name: string;
      /**
       * @description Category description
       * @example Category description
       */
      description: string | null;
      /**
       * @description Category color code
       * @example #000000
       */
      colorCode: string | null;
      /**
       * Format: date-time
       * @description Category created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Category updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    ItemResponseDto: {
      /**
       * @description Item uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Item name
       * @example Item name
       */
      name: string;
      /**
       * @description Item description
       * @example Item description
       */
      description: string | null;
      /**
       * @description Item weight
       * @example 100
       */
      weight: number | null;
      /** @description Item category */
      category: components['schemas']['CategoryResponseDto'] | null;
      /**
       * Format: date-time
       * @description Item created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Item updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    ItemWithQuantityResponseDto: {
      /**
       * @description Item quantity
       * @example 1
       */
      quantity: number;
      /** @description Item */
      item: components['schemas']['ItemResponseDto'];
    };
    ListResponseDto: {
      /**
       * @description List uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description List name
       * @example List name
       */
      name: string;
      /**
       * @description List description
       * @example List description
       */
      description: string | null;
      /**
       * @description List color code
       * @example #000000
       */
      colorCode: string | null;
      /**
       * Format: date-time
       * @description List created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description List updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
      /** @description Items on list */
      items?: components['schemas']['ItemWithQuantityResponseDto'][];
    };
    ListWithQuantityResponseDto: {
      /**
       * @description List quantity
       * @example 1
       */
      quantity: number;
      /** @description List */
      list: components['schemas']['ListResponseDto'];
    };
    PackResponseDto: {
      /**
       * @description Pack uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Pack name
       * @example Pack name
       */
      name: string;
      /**
       * @description Pack description
       * @example Pack description
       */
      description: string | null;
      /**
       * @description Pack color code
       * @example #000000
       */
      colorCode: string | null;
      /**
       * Format: date-time
       * @description Pack created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Pack updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
      /** @description Items in pack */
      items?: components['schemas']['ItemWithQuantityResponseDto'][];
      /** @description Lists in pack */
      lists?: components['schemas']['ListWithQuantityResponseDto'][];
    };
    TripResponseDto: {
      /**
       * @description Trip uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Trip name
       * @example Trip name
       */
      name: string;
      /**
       * Format: date-time
       * @description Trip date
       * @example 2026-01-01T00:00:00.000Z
       */
      date: string | null;
      /**
       * @description Trip remarks
       * @example Trip remarks
       */
      remarks: string | null;
      /** @description Pack used in trip */
      pack: components['schemas']['PackResponseDto'];
      /**
       * Format: date-time
       * @description Trip created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Trip updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
    ItemDeleteImpactDto: {
      item: components['schemas']['ItemResponseDto'];
      lists: components['schemas']['ListResponseDto'][];
      packs: components['schemas']['PackResponseDto'][];
      trips: components['schemas']['TripResponseDto'][];
    };
    CreateItemDto: {
      /**
       * @description Item name
       * @example Item name
       */
      name: string;
      /**
       * @description Item description
       * @example Item description
       */
      description?: string;
      /**
       * @description Item weight
       * @example 100
       */
      weight?: number | null;
      /**
       * Format: uuid
       * @description Item category uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      categoryId?: string;
    };
    UpdateItemDto: {
      /**
       * @description Item name
       * @example Item name
       */
      name?: string;
      /**
       * @description Item description
       * @example Item description
       */
      description?: string;
      /**
       * @description Item weight
       * @example 100
       */
      weight?: number | null;
      /**
       * Format: uuid
       * @description Item category uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      categoryId?: string;
    };
    CategoryDeleteImpactDto: {
      category: components['schemas']['CategoryResponseDto'];
      items: components['schemas']['ItemResponseDto'][];
    };
    CreateCategoryDto: {
      /**
       * @description Category name
       * @example Category name
       */
      name: string;
      /**
       * @description Category description
       * @example Category description
       */
      description?: string;
      /**
       * @description Category color code
       * @example #000000
       */
      colorCode?: string;
    };
    UpdateCategoryDto: {
      /**
       * @description Category name
       * @example Category name
       */
      name?: string;
      /**
       * @description Category description
       * @example Category description
       */
      description?: string;
      /**
       * @description Category color code
       * @example #000000
       */
      colorCode?: string;
    };
    ListSummaryResponseDto: {
      /**
       * @description List uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description List name
       * @example List name
       */
      name: string;
      /**
       * @description List description
       * @example List description
       */
      description: string | null;
      /**
       * @description List color code
       * @example #000000
       */
      colorCode: string | null;
      /**
       * Format: date-time
       * @description List created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description List updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
      /**
       * @description List item count
       * @example 1
       */
      itemCount: number;
    };
    ListDeleteImpactDto: {
      list: components['schemas']['ListSummaryResponseDto'];
      packs: components['schemas']['PackResponseDto'][];
      trips: components['schemas']['TripResponseDto'][];
    };
    CreateListDto: {
      /**
       * @description List name
       * @example List name
       */
      name: string;
      /**
       * @description List description
       * @example List description
       */
      description?: string;
      /**
       * @description List color code
       * @example #000000
       */
      colorCode?: string;
    };
    UpdateListDto: {
      /**
       * @description List name
       * @example List name
       */
      name?: string;
      /**
       * @description List description
       * @example List description
       */
      description?: string;
      /**
       * @description List color code
       * @example #000000
       */
      colorCode?: string;
    };
    PackSummaryResponseDto: {
      /**
       * @description Pack uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * @description Pack name
       * @example Pack name
       */
      name: string;
      /**
       * @description Pack description
       * @example Pack description
       */
      description: string | null;
      /**
       * @description Pack color code
       * @example #000000
       */
      colorCode: string | null;
      /**
       * Format: date-time
       * @description Pack created at
       * @example 2026-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description Pack updated at
       * @example 2026-01-01T00:00:00.000Z
       */
      updatedAt: string;
      /**
       * @description Pack item count
       * @example 1
       */
      itemCount: number;
      /**
       * @description Pack list count
       * @example 1
       */
      listCount: number;
    };
    PackDeleteImpactDto: {
      pack: components['schemas']['PackSummaryResponseDto'];
      trips: components['schemas']['TripResponseDto'][];
    };
    CreatePackDto: {
      /**
       * @description Pack name
       * @example Pack name
       */
      name: string;
      /**
       * @description Pack description
       * @example Pack description
       */
      description?: string;
      /**
       * @description Pack color code
       * @example #000000
       */
      colorCode?: string;
    };
    UpdatePackDto: {
      /**
       * @description Pack name
       * @example Pack name
       */
      name?: string;
      /**
       * @description Pack description
       * @example Pack description
       */
      description?: string;
      /**
       * @description Pack color code
       * @example #000000
       */
      colorCode?: string;
    };
    CreateTripDto: {
      /**
       * @description Trip name
       * @example Trip name
       */
      name: string;
      /**
       * Format: date-time
       * @description Trip date
       * @example 2026-01-01T00:00:00.000Z
       */
      date?: string;
      /**
       * @description Trip remarks
       * @example Trip remarks
       */
      remarks?: string;
      /**
       * @description Pack uuid associated with the trip
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      packId: string | null;
    };
    UpdateTripDto: {
      /**
       * @description Trip name
       * @example Trip name
       */
      name?: string;
      /**
       * Format: date-time
       * @description Trip date
       * @example 2026-01-01T00:00:00.000Z
       */
      date?: string;
      /**
       * @description Trip remarks
       * @example Trip remarks
       */
      remarks?: string;
      /**
       * @description Pack uuid associated with the trip
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      packId?: string | null;
    };
    UpsertItemOnListDto: {
      /**
       * @description Item uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      itemId: string;
      /**
       * @description List uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      listId: string;
      /**
       * @description Item quantity
       * @example 1
       */
      quantity: number;
    };
    UpsertItemInPackDto: {
      /**
       * @description Item uuid
       * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
       */
      itemId: string;
      /**
       * @description Pack uuid
       * @example b2c3d4e5-f6a7-8901-bcde-f12345678901
       */
      packId: string;
      /**
       * @description Item quantity
       * @example 1
       */
      quantity: number;
    };
    UpsertListInPackDto: {
      /**
       * @description List uuid
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      listId: string;
      /**
       * @description Pack uuid
       * @example 987fcdeb-51a2-3bc4-d567-890123456789
       */
      packId: string;
      /**
       * @description List quantity
       * @example 1
       */
      quantity: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ItemController_getItems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Items retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemResponseDto'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemController_createItem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateItemDto'];
      };
    };
    responses: {
      /** @description Item created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemController_getItemDeleteImpact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item deletion impact retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemDeleteImpactDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Item not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemController_getItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemResponseDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Item not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemController_deleteItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item deleted successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Item not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemController_updateItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateItemDto'];
      };
    };
    responses: {
      /** @description Item updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ItemResponseDto'];
        };
      };
      /** @description Validation failed (invalid UUID v7 format or invalid body). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Item not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoryController_getCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Categories retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponseDto'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoryController_createCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryDto'];
      };
    };
    responses: {
      /** @description Category created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoryController_getCategoryDeleteImpact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Category deletion impact retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryDeleteImpactDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Category not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoryController_getCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Category retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponseDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Category not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoryController_deleteCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Category deleted successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Category not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CategoryController_updateCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCategoryDto'];
      };
    };
    responses: {
      /** @description Category updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryResponseDto'];
        };
      };
      /** @description Validation failed (invalid UUID v7 format or invalid body). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Category not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListController_getLists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lists retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListResponseDto'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListController_createList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateListDto'];
      };
    };
    responses: {
      /** @description List created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListController_getListDeleteImpact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List deletion impact retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListDeleteImpactDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description List not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListController_getList: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListResponseDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description List not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListController_deleteList: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List deleted successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description List not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListController_updateList: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateListDto'];
      };
    };
    responses: {
      /** @description List updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ListResponseDto'];
        };
      };
      /** @description Validation failed (invalid UUID v7 format or invalid body). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description List not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PackController_getPacks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Packs retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PackResponseDto'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PackController_createPack: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePackDto'];
      };
    };
    responses: {
      /** @description Pack created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PackResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PackController_getPackDeleteImpact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pack deletion impact retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PackDeleteImpactDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Pack not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PackController_getPack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pack retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PackResponseDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Pack not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PackController_deletePack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pack deleted successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Pack not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PackController_updatePack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePackDto'];
      };
    };
    responses: {
      /** @description Pack updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PackResponseDto'];
        };
      };
      /** @description Validation failed (invalid UUID v7 format or invalid body) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Pack not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TripController_getTrips: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trips retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponseDto'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TripController_createTrip: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTripDto'];
      };
    };
    responses: {
      /** @description Trip created successfully. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponseDto'];
        };
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TripController_getTrip: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trip retrieved successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponseDto'];
        };
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trip not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TripController_deleteTrip: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trip deleted successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (uuid v7 is expected) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trip not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TripController_updateTrip: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTripDto'];
      };
    };
    responses: {
      /** @description Trip updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TripResponseDto'];
        };
      };
      /** @description Validation failed (invalid UUID v7 format or invalid body). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Trip not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemListController_upsertItemOnList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertItemOnListDto'];
      };
    };
    responses: {
      /** @description Item upserted to list successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemListController_removeItemFromList: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: string;
        listId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item removed from list successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (invalid UUID v7 format). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemPackController_upsertItemInPack: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertItemInPackDto'];
      };
    };
    responses: {
      /** @description Item upserted to pack successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ItemPackController_removeItemFromPack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: string;
        packId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Item removed from pack successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (invalid UUID v7 format). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListPackController_upsertListInPack: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpsertListInPackDto'];
      };
    };
    responses: {
      /** @description List upserted to pack successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (dto) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListPackController_removeListFromPack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listId: string;
        packId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List removed from pack successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation failed (invalid UUID v7 format). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description ThrottlerException: Too Many Requests. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
